version: '3'

services:
  db:
    image: postgres
    volumes:
      - python_learning_site:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  python_learning_site:
